name: create-nuget-package

on:
  push:
    tags:
    - 'v*'
  workflow_dispatch:
    
env:
  PROJECT_PATH: 'src/Ieg.Sequencer/Ieg.Sequencer.csproj'
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}/output
  NUGET_SOURCE_URL: 'https://api.nuget.org/v3/index.json'
  
jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        dotnet-version: [ '6.0.x' ]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      
      - name: 'Install dependencies'
        run: dotnet restore  ${{ env.PROJECT_PATH }}
      
      - name: 'Build project'
        run: dotnet build ${{ env.PROJECT_PATH }} --no-restore --configuration Release
      
      #- uses: actions/checkout@v3
      - name: 'Get Version'
        uses: bbonkr/get-version-action@v1.0.4
        id: get_version
        with:
          project: ${{ env.PROJECT_PATH }}
      
      - name: 'log version'
        run: echo "Version=${{ steps.get_version.outputs.version }}"

      - name: 'Pack project'
        run: dotnet pack ${{ env.PROJECT_PATH }} --no-restore --no-build --configuration Release --include-symbols -p:PackageVersion=${{ steps.get_version.outputs.version }} --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}

      - name: 'Push package'
        run: dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIRECTORY }}/*.nupkg -k ${{ secrets.NUGET_OPEN_SOURCE }} -s ${{ env.NUGET_SOURCE_URL }}
